services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
    command: sh -c "yarn dev"
    environment:
      - VITE_BASE_API_URL=https://localhost:8000/api/v1
  db:
    image: postgis/postgis:15-3.4
    volumes:
      - postgis_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=truequeardb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=truequeardb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_CONFIGURATION=Dev
      - DJANGO_SETTINGS_MODULE=barter.settings
      - DJANGO_SECRET_KEY=mySuperKey
      - DJANGO_CORS_ALLOWED_ORIGINS=http://localhost:3000
      - DJANGO_ALLOWED_HOSTS=http://localhost:3000;localhost
    depends_on:
      - db

volumes:
  postgis_data:
