name: Build and push images

on:
  push:
    branches:
      - main

env:
  REGISTRY: ghcr.io

jobs:
  build-and-push-images:
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # -
      #   name: Build and push
      #   uses: docker/build-push-action@v4
      #   with:
      #     context: ./client
      #     build-args: |
      #       "VITE_API_BASE_URL=${{ vars.VITE_MILLEROS_BASE_URL }}"
      #       "VITE_GOOGLE_ANALYTICS_ID=${{ vars.VITE_GOOGLE_ANALYTICS_ID }}"
      #     push: true
      #     tags: |
      #       ${{ env.REGISTRY }}/${{ github.repository }}/client:${{ github.sha }}
      #       ${{ env.REGISTRY }}/${{ github.repository }}/client:${{ vars.SUFFIX_IMAGE }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./server
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ github.sha }}
            ${{ env.REGISTRY }}/${{ github.repository }}/server:${{ vars.SUFFIX_IMAGE }}
      - name: Trigger ArgoCD Sync
        run: |
          curl -X POST -k https://argocd.milleros.com.ar/api/v1/applications/barter-prd/sync \
            -H "Authorization: Bearer ${{ secrets.ARGOCD_API_TOKEN }}" \
            -H "Content-Type: application/json" -d '{"syncOptions":{"items":["CreateNamespace=true","Replace=true"]}}'
